[package]
name = "::name::"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
schemars = "0.8"

[dependencies.near]
package = "near-sdk"
git = "https://github.com/near/near-sdk-rs.git"
rev = "1f9a7b23b943b6c8ee4d1db2c2427a2b5f0716bb"
features = ["abi"]

[workspace]
members = []

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
