[package]
name = "::name::"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
schemars = "0.8"

[target.'cfg(windows)'.dependencies]
# NOTE: uncomment line 15 and comment 16, if it's desirable to switch to published `near-sdk` version
# near-sdk = { ::sdk-cratesio-version-toml:: }
near-sdk = { ::sdk-git-version-toml:: }

[target.'cfg(unix)'.dependencies]
# NOTE: uncomment line 20 and comment 21, if it's desirable to switch to published `near-sdk` version
# near-sdk = { ::sdk-cratesio-version-toml:: }
near-sdk = { ::sdk-git-version-toml:: }

[workspace]
members = []

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
